### ISSUE TITLE
Example: how to iterate an unnamed array of objects

### ISSUE THREAD

**Issue by andersborgabiro** [pcrov/JsonReader#15]
Thanks for JsonReader.

Below is very typical for a response from an API or contents of a JSON file, in my case historical weather data, with this structure.

    [
        { object 1 },
        { object 2 },
        ...
    ]

An example showing how to iterate through this so that each value would be each top object would be very nice. At least I couldn't figure it out. What's in each object varies, so each value should be the complete (sub) object for later analysis.

When I tried JsonReader::ARRAY, then value used up all memory (100 MB JSON with ~260000 objects (30 years * 365 days * 24 hours)).

Thanks in advance.

**Comment by andersborgabiro** [comment]
I got the output I needed with this code, but maybe not in an optimal way. Could this be simplified somehow?

    $reader = new JsonReader();
    $reader->json($json);

    $count = 0;
    $reader->read();
    while (true):
        if ($reader->type() === JsonReader::OBJECT):
            $data = $reader->value();

            $row = [
                'timestamp' => intval($data['dt']),
                'id_weatherlocations' => BULKLOCATION,
                'weather' => json_encode($data)
            ];

            //sqlinsert('weatherdatabulk', $row);            

            $reader->next();
            $count++;
        else:
            $reader->read();
        endif;
    endwhile;
    $reader->close();

**Comment by pcrov** [comment]
This might be sufficient for what you've got:

```php
$reader = new JsonReader();
$reader->json($json);

$reader->read(); // Begin array
$reader->read(); // Step to the first element
while($reader->type() === JsonReader::OBJECT) {
    $data = $reader->value();
    $row = [
        'timestamp' => intval($data['dt']),
        'id_weatherlocations' => BULKLOCATION,
        'weather' => json_encode($data),
    ];
    sqlinsert('weatherdatabulk', $row);

    $reader->next();
}

$reader->close();
```

I've added a variation of this as [Example 5](https://github.com/pcrov/JsonReader/wiki/Examples#example-5).

**Comment by andersborgabiro** [comment]
Great! Many thanks.

I guess the json_encode is a bit odd, but I want to store raw data, so I can handle possible oddities in the data when using it, rather than at this stage.

**Comment by andersborgabiro** [comment]
I made a minor change to handle invalid data.

$reader->read();
if ($reader->type() === JsonReader::ARRAY) {
    $reader->read();
    while($reader->type() === JsonReader::OBJECT) {
        $data = $reader->value();

        // Do something with the data

        $reader->next();
    }
}
