### ISSUE TITLE
Feature - Skip file content

### ISSUE THREAD

**Issue by ErwinSanquer** [pcrov/JsonReader#17]
Hello,

Thank you for this great package. Im trying to use it to read a .json generated by phpmyadmin. It have several comments at the top of the file /* */ and // which throw an exception and no way to remove them when the file is generated, except by updating the code source of phpmyadmin.

`pcrov\JsonReader\Parser\ParseException  : Line 1: Unexpected '/'.`

Is there a way to skip a part of the file or to allow comment ?

Thanks

**Comment by pcrov** [comment]
From https://github.com/phpmyadmin/phpmyadmin/issues/12307 it looks like this was fixed on the phpmyadmin side in 4.7.0 which means the version you're using is many years out of date. If the only problem was the leading comments I'd suggest writing a [custom input stream](https://github.com/pcrov/JsonReader/wiki/Custom-Input) that skips them, however there are multiple [other](https://github.com/phpmyadmin/phpmyadmin/issues/12307#issuecomment-225792103) [issues](https://stackoverflow.com/q/21265975/3942918) you're likely to run into causing your json to be invalid.

Considering these plus the security issues of running such an old version of phpmyadmin, I strongly recommend upgrading to a currently supported version available at https://www.phpmyadmin.net/downloads/.
