### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by henzeb** [pcrov/JsonReader#21]
Hi, 

will there be PHP 8.0 support?

**Comment by pcrov** [comment]
PHP 8 has been supported since [1.0.1](https://github.com/pcrov/JsonReader/releases/tag/1.0.1). Have you run into a problem with it?

**Comment by henzeb** [comment]
My bad, the errors in composer showed a php version mismatched as first version, including the last update being a month before the official release, having bumped into this issue a multiple times now, made me assume this was the cause, I just missed ext-intl.

**Comment by pcrov** [comment]
No worries, glad you got it sorted.
