### ISSUE TITLE
Negative exponents throw MalformedJsonException

### ISSUE THREAD

**Issue by agjmills** [pcrov/JsonReader#23]
If you have a very small float, such as 1.2e-5 (0.000012) a MalformedJsonException is thrown as it fails the logic in JsonReader.php:377

**Comment by pcrov** [comment]
JsonReader.php has no line 377, nor does anything in this package throw a MalformedJsonException. In addition I've tested 1.2e-5 and it parses just fine. Are you sure you're using this JsonReader?

**Comment by agjmills** [comment]
My bad - wrong JsonReader! Apologies!
