### ISSUE TITLE
Make "ext-intl" dependency optional

### ISSUE THREAD

**Issue by MurzNN** [pcrov/JsonReader#25]
I use your package as dependency of my package, and very often my users got confused about errors in composer, because their systems are missing of `ext-intl` extension. I know, that it's needed for encode symbols from JSON as UTF-8. 

But in my situation all JSON files contain only ASCII characters, so UTF-8 decoder is not needed, but still required. And there are many other cases when UTF-8 decoding is not needed.

To solve this problem will be good to make "ext-intl" dependency optional, and throw an exception with describing needing of it only when we catch UTF-8 characters.

Or, as alternative, provide another clone of this package, but without "ext-intl" dependency. 

What do you think about this idea?

**Comment by pcrov** [comment]
I'd consider depending on a polyfill if one's available, or possible just reimplementing things. Lemme poke around.

**Comment by pcrov** [comment]
This is probably not going to happen without a polyfill and I'm not finding one out there. There is symfony/polyfill-intl-icu however it doesn't provide IntlChar which the lexer uses - and it uses it more than I'm likely to reimplement any time soon. Some of the code would be easy enough to replace however it'd take thorough testing for both correctness and performance.

Regarding your suggested alternatives:

> throw an exception with describing needing of it only when we catch UTF-8 characters

This would make it a nasty hidden dependency, possibly only discovered when a user runs into particular data in production. I'm not comfortable with that.

> Or, as alternative, provide another clone of this package, but without "ext-intl" dependency.

Without actually gutting it to remove the use this just falls back into the hidden dependency problem, and I'm not going to maintain a second package for parsing only a subset of JSON.

If you can find a polyfill that'd be excellent. All that'd be needed then would be to tweak the test matrix to run both with and with the extension.

**Comment by MurzNN** [comment]
Maybe just reuse `json_decode` functionality for escaped strings? Something like this seems works without `php-intl`:
```
$var = '"\u0436\u0430\u0440\u043A\u043E"';
var_dump( json_decode($var));
```

**Comment by pcrov** [comment]
That is one possibility, yes, though IntlChar is not only used for dealing with escaped strings. Doing this would also trade one dependency for another as the JSON extension isn't guaranteed to be there in PHP 7.

**Comment by MurzNN** [comment]
Yes, but `php-json` are much more often installed by default, than `php-intl`, for example in very old Debian family it is installed by default with PHP: 
https://packages.debian.org/stretch/php7.0-cgi
https://packages.debian.org/stretch/php7.0-fpm
https://packages.debian.org/stretch/php7.0-cli

**Comment by pcrov** [comment]
Yep, I'm aware. I've considered overhauling string handling entirely to use the JSON extension for a while now. At least for the happy path of valid JSON. (The unhappy path would probably still need help in order to produce better error messages.) It's work I've been putting off largely because it'd fit better in a year when PHP 7 support ends. Plus it's not clear how much would be gained doing it anyway.

**Comment by pcrov** [comment]
Holler if you run into a polyfill for IntlChar. Without one this is gonna be a wontfix for at least a year.
