### ISSUE TITLE
Maybe the wrong place -- Wiki Edit

### ISSUE THREAD

**Issue by avizaz** [pcrov/JsonReader#6]
I'm kind of a newbie in github,
Thanks a lot for this amazing script, instead of 20s loading time it takes less than a second!

I think many people will enjoy this following example so please consider adding to wiki (as I can't seem to be able to) -- for some reason this is missing from the examples yet it should be basic:

Found part of it in stackoverflow and it is modified a bit
`/* data.json

[{"event_id":"943815","name":"AT&T Byron Nelson Golf Championship - Thursday Competition","url":"http:\/\/www.ticketmonster.com\/buy-AT&T-Byron-Nelson-Golf-Championship---Thursday-Competition-tickets-at-TPC-Four-Seasons-Resort-Las-Colinas-Irving-Texas-05-18-2017\/943815?aid=20770","datetime":"2017-05-18T08:00:00Z","performers":[{"performer_id":"24797"},{"performer_id":"1714920"}],"categories":[{"category_id":"1"},{"category_id":"10"}],"venue":{"city":"Irving","state":"Texas","name":"TPC Four Seasons Resort Las Colinas","venue_id":"20017"}},{"event_id":"993368","name":"Scranton\/Wilkes-Barre RailRiders vs. Pawtucket Red Sox","url":"http:\/\/www.ticketmonster.com\/buy-Scranton\/Wilkes-Barre-RailRiders-vs.-Pawtucket-Red-Sox-tickets-at-PNC-Field-Scranton-Pennsylvania-05-18-2017\/993368?aid=20770","datetime":"2017-05-18T10:35:00Z","performers":[{"performer_id":"15966"},{"performer_id":"3629"}],"categories":[{"category_id":"1"},{"category_id":"5"}],"venue":{"city":"Scranton","state":"Pennsylvania","name":"PNC Field","venue_id":"12805"}}]

*/

$reader = new JsonReader();
$reader->open("data.json");

$reader->read(); // Outer array.
$depth = $reader->depth(); // Check in a moment to break when the array is done.

$reader->read(); // Step to the first object.
while ($reader->next() && $reader->depth() > $depth) {// Read each sibling.
	print_r($reader->value());
} 

$reader->close();`

**Comment by pcrov** [comment]
Thank you for the suggestion. I've added [example 4](https://github.com/pcrov/JsonReader/wiki/Examples#example-4). It's similar to what you've got but changed to use the existing sample data and to not skip outputting the first element of the array.

If there's any other documentation you feel would be useful please do continue to open issues here, the wiki isn't open for public edits.
