### ISSUE TITLE
Large Json file

### ISSUE THREAD

**Issue by kabus202** [pcrov/JsonReader#8]
Hi,

How to deal with large json files? (2GB json file). My php file gets 'Killed' by the console. 
This is my code:

`<?php

require 'vendor/autoload.php';

use pcrov\JsonReader\JsonReader;

$reader = new JsonReader();
$reader->open("2018.json");

while($reader->read()) {

        print_r($reader->value()); 
  
  }

$reader->close();
?>`

**Comment by PeeHaa** [comment]
Are you on 32b PHP?

**Comment by kabus202** [comment]
Running:  **PHP 7.0.25-1~dotdeb+8.1 (cli) ( NTS )**  64 bit

**Comment by pcrov** [comment]
When the current node is an array or object `$reader->value()` needs to parse the node in its entirety to produce the return value (simple types like numbers and strings have already been parsed and are immediately available.) So when you use it on a top level object or array you're parsing the full document and building the entire result in memory - at which point you'd be better off using [json_decode](http://php.net/json_decode) instead. With a 2GB json file I'd expect this to fall on its face.

You'll want to use the reader to traverse through your document and grab only the bits you need. There are a few [examples on the wiki](https://github.com/pcrov/JsonReader/wiki/Examples) though how best to handle your particular json will depend on its structure and what you need out of it.

**Comment by kabus202** [comment]
Thanks @pcrov  json_decode did  the trick! 👍
